version: '3'
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRESS_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRESS_DB: product-service
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres

networks:
  devicehub-network:

volumes:
  postgres-data:







