spring:
  application:
    name: DeviceHub eCommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    validate-on-migrate: true
  sql:
    init:
      mode: never
